- name: stoppo il servizio crond    
  service: name=crond state=stopped

- name: scompatto la cartella {{ src_tar }}
  unarchive:
    src: "{{ src_rdp }}/etl.tar.gz"
    dest: /var/opt/pentaho/statistics/