- name: stoppo il servizio crond    
  service: name=crond state=stopped

- name: scompatto la cartella {{ src_rdp }}/etl.tar.gz
  unarchive:
    src: "{{ src_rdp }}/etl.tar.gz"
    dest: /var/opt/pentaho/statistics/
    
- name: scompatto la cartella 
  unarchive:
    src: "{{ src_rdp }}/pentaho8/pdi-ce-8.0.0.0-28.tar.gz"
    dest: /var/opt/pentaho/
    extra_opts: "--overwrite --overwrite-dir"
    owner: root
    group: root
    mode: 0755
    