# tasks file for 6585
- name: resoconto in file {{ logfile }}
  shell: echo "Applicato il bug {{bug}} dall'utente $USER in data $(date +%d-%m-%Y_%H:%M:%S) sui server {{inventory_hostname}} " >> {{ logfile }}
  delegate_to: localhost
  changed_when: false
- name: resoconto in database ansible
  shell: mysql --user=ansible_update --password=$(cat /home/password_insert) -e "insert into ansible.bugs values ( '{{bug}}','$USER','$(date +%d-%m-%Y_%H:%M:%S)','{{inventory_hostname}}');"
  delegate_to: localhost
  changed_when: false


- include: check_parameter.yml
  delegate_to: localhost
  run_once: true
  
  # prima di partire con l'aggiornamento di EasyCIM 3.6.3 controllo che il primo server cti abbia pacchetto 7.0.5
  # Se non specifico nessun parametro contact, il riferimento viene preso guardando la macchina pentaho
- include: check_contact_version.yml
  when: ( contact is not defined and inventory_hostname == pentaho ) or ( contact is defined and inventory_hostname == contact )
  
- include: undeploy_applicazioni.yml
  when: "'ecas' in inventory_hostname"
  with_items:
  - 'agentdesktopmanager-'
  - 'EasyCIM-'
  - 'TaskManagerSystem-'
  - 'WorkflowManager-'
  - 'easyintegration-'    


- include: present_tomcat.yml
  when: inventory_hostname == pentaho

- include: etl_step1.yml
  when: inventory_hostname == etl
  
- include: database_step.yml
  when: inventory_hostname == database
  
- include: install_report.yml
  when: "'ecas' in inventory_hostname"  

- include: etl_step2.yml
  when: inventory_hostname == etl  
  
