- name: Controllo se su questo server esiste l'applicazione agentdesktopMGR
  shell: "asadmin list-applications | grep {{ item }}"
  failed_when: false
  check_mode: false
  environment:
      PATH: "{{ ansible_env.PATH }}:/usr/java/default/bin:/opt/glassfish/bin/"
  register: app_presente

- name: "undeploy l' applicazione  {{ item }}"
  shell: "asadmin undeploy {{ app_presente.stdout.split(' ')[0] }}"
  when:  app_presente.rc == 0 and app_presente is defined and app_presente.rc is defined
   
           